att_fn: xmea
aux_loop: null
aux_scale: 0.1
aux_smooth: 0.1
aux_struct: null
batch_size: 250
d_heads: 48
emb_grad_frac: 1
epoch_ensemble: 5
ffn_bias: false
ffn_multi: 4
fold: 4
grad_clip: 5
kernel_size_gc: 3
lr: 0.002
lr_warmup: 0.015
n_epochs: 200
n_folds: 5
n_grad_accum: 2
n_heads: 6
n_heads_rnn: 2
n_layers: 12
n_layers_rnn: 1
n_mem: 0
norm_lax: false
norm_layout: dual
norm_rms: true
note: ''
p_dropout: 0.1
p_flip: 0.5
pos_bias_heads: 6
pos_bias_params: !!python/tuple
- 32
- 128
pos_rope: false
pos_sine: false
qkv_bias: false
seed: 420
sn_min: 0.6
stochastic_weight_average: false
tta_flip: true
use_lenmatched_batch: true
val_flip: true
wt_decay: 0.1
