att_fn: xmea
aug_reverse: true
aux_loop: null
aux_scale: 0.1
aux_smooth: 0.1
aux_struct: null
batch_size: 250
d_heads: 48
emb_grad_frac: 1
ffn_bias: false
ffn_multi: 4
fold: 2
grad_clip: 5
kernel_size_gc: 7
lr: 2.0e-05
lr_warmup: 0.015
n_epochs: 200
n_folds: 5
n_grad_accum: 1
n_heads: 6
n_layers: 12
n_layers_lstm: 1
n_mem: 0
norm_lax: false
norm_layout: dual
norm_rms: true
note: ''
p_dropout: 0.1
pos_bias_heads: 6
pos_bias_params: !!python/tuple
- 32
- 128
pos_rope: false
pos_sine: false
qkv_bias: false
seed: 420
sn_min: 0.6
use_lenmatched_batch: true
wt_decay: 0.1
